baseURL = "https://blog.junjie.pro/"
languageCode = "zh-cn"
title = "Junjie's Blog"
theme = "ananke"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"

[params]
  favicon = "favicons/material_icon_outline_dns_black_24px.svg"

