stages:
  - build
  - deploy

test:
  stage: build
  image: jojomi/hugo
  except:
  - master
  script:
  - git submodule update --init --recursive
  - hugo version
  - HUGO_ENV="production" hugo
  artifacts:
    paths:
    - public

pages:
  stage: deploy
  image: jojomi/hugo
  only:
  - master
  script:
  - git submodule update --init --recursive
  - hugo version
  - HUGO_ENV="production" hugo
  artifacts:
    paths:
    - public
