stages:
  - test
  - deploy

test job:
  stage: test
  image: jojomi/hugo
  except:
  - master
  script:
  - hugo version
  - git submodule update --init --recursive
  - HUGO_ENV="production" hugo
  artifacts:
    paths:
    - public

pages:
  stage: deploy
  image: jojomi/hugo
  only:
  - master
  script:
  - hugo version
  - git submodule update --init --recursive
  - HUGO_ENV="production" hugo
  artifacts:
    paths:
    - public

