baseURL = "https://blog.ceiling.cloud/"
languageCode = "zh-cn"
title = "Blog | Project Ceiling"
theme = "ananke"
# googleAnalytics = ""

[menu]
  [[menu.main]]
    identifier = "about"
    name = "关于我们"
    url = "/about/"
