baseURL = "https://ceiling.cloud/"
languageCode = "zh-cn"
title = "Project Ceiling"
theme = "ananke"
googleAnalytics = "UA-126801232-2"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "关于我们"
    url = "/about/"

